### ISSUE TITLE
Release new version on PyPI for Django 1.6

### ISSUE THREAD

**Issue by vdboor** [gnotaras/django-taggit-autocomplete-modified#5]
Could you release a new version of django-taggit-autocomplete-modified for Django 1.6?

p.s. I tried to fill in your contact form (as I wasn't sure github or redmine was the proper place, but that form doesn't seem to be working)

**Comment by gnotaras** [comment]
Hi, `0.1.0b5` has been released to PyPI. Please feel free to report any issues.

**Comment by gnotaras** [comment]
Currently, I don't use this app with a recent Django release. Any feedback at any time about whether it works fine with 1.9.X or not would be greatly appreciated.

**Comment by vdboor** [comment]
Unfortunately, I've stopped using this app on newer Django versions, so I can't really tell right now either. I'm using django-taggit-autosuggest now.

**Comment by gnotaras** [comment]
OK, I might try to test it with Django 1.9.X in one of the following days. Thanks for your feedback!
